import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import StyledComponentsRegistry from '../lib/registry'
const inter = Inter({ subsets: ['latin'] })
import ThemeRegistry from "../lib/ThemeRegistry"; 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <ThemeRegistry>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ThemeRegistry>
      </body>
    </html>
  )
}

